abacoui:
  name: abaco-ui
  image:
    repository: basis-registry.basis.com.br/abaco/abaco-ui
    tag: teste
  replicaCount: 1
  ingress:
    url: "abaco.tst.basis.com.br"
  ports:
    port: 80
  imagePullSecrets:
  - name: basis-registry
  proxy:
    locations:
    - abaco

abaco:
  name: abaco
  image:
    repository: basis-registry.basis.com.br/abaco/abaco
    tag: teste
  replicaCount: 1
  ports:
    port: 8080
  health:
    disabled: true
  imagePullSecrets:
  - name: basis-registry
  configmap:
    spring:
      profiles:
        active: "prod,swagger"
      datasource:
        url: jdbc:postgresql://pgsql-abaco/abaco
        username: abaco
        password: abaco
      jackson:
        serialization.write_dates_as_timestamps: false
      data:
        elasticsearch:
          cluster-name: abaco
          cluster-nodes: es-abaco-tst-client:9300
    
elasticsearch:
  install: true
  fullnameOverride: es-abaco-tst
  image:
    repository: "elasticsearch"
    tag: "2.4-alpine"
  cluster:
    name: abaco
  data:
    replicas: 2
    persistence:
      size: 4Gi
      storageClass: nfs-name
  master:
    replicas: 2
    persistence:
      storageClass: nfs-name
      size: 4Gi
  client:
    replicas: 1
    exposeTransportPort: true

postgresql:
  install: true
  imageTag: 11.4.0
  fullnameOverride: pgsql-abaco
  postgresqlUsername: abaco
  postgresqlPassword: abaco
  postgresqlDatabase: basis
  persistence:
    storageClass: nfs-name
    size: 10Gi